spring.application.name=employee-management-system
spring.datasource.url=jdbc:postgresql://localhost:5332/company_db
spring.datasource.username=maksluczak
spring.datasource.password=S3cret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true